var g={
	siteid:null,
	datataken:null,
	metertype:null,
	spintestbefore:null,
	spintestafter:null,
	measureddevice:null,
	measuredfrom:null,
	measuredvalue:null,
	winddirection:null,
	windspeed:null,
	angletype:null,
	anglecurrent:null,
	watercolour:null,
	watercolour:null,
	stagereadings:[{
	type:null,
	time:null,
	recorder:null,
	well:null,
	gauge:null,
	diff:null
	}],
	computeddischarge:null,
	computedarea:null,
	computedmeanvel:null,
	readingremark:null
};
